
const translations = {
  es: {

    "service1": "✓ Terapia Online (Cognitivo-Conductual)",
    "service2": "✓ Manejo de Ansiedad y Depresión",
    "service3": "✓ Terapia para Padres con Hijos Adictos",
    "servicesTitle": "Servicios"

    "404_key1": "Inicio",
    "404_key2": "Sobre mí",
    "404_key3": "Contacto",
    "404_key4": "404",
    "404_key5": "Página no encontrada",
    "404_key6": "Lo sentimos, la página que buscas no existe.",
    "404_key7": "Volver al Inicio",
    "about_key1": "Inicio",
    "about_key2": "Sobre mí",
    "about_key3": "Contacto",
    "about_key4": "Hola, soy Rosina. ¡Bienvenido a mi página! Soy Psicóloga con cinco años de experiencia trabajando con una amplia variedad de pacientes y situaciones.",
    "about_key5": "Durante dos años formé parte del equipo de un centro psiquiátrico, lo que me permitió adquirir un sólido manejo en el abordaje de diversas problemáticas.",
    "about_key6": "Tengo experiencia en el tratamiento de depresión, duelos por separación, baja autoestima, trastorno bipolar, trastornos de ansiedad, trastorno límite de la personalidad, esquizofrenia, adicciones, entre otros.",
    "about_key7": "También he trabajado como profesora en la Universidad de la República (UDELAR) y en Recursos Humanos.",
    "about_key8": "Actualmente me dedico a mi gran pasión: la atención clínica personalizada de pacientes con un enfoque cognitivo-conductual.",
    "about_key9": "Agendar una Cita",
    "about_key10": "Rosina Rey",
    "about_key11": "Rosina.rey.asis@gmail.com",
    "about_key12": "+598 9820 3870",
    "about_key13": "Privacidad",
    "about_key14": "Términos",
    "about_key15": "Accesibilidad",
    "about_key16": "No vender ni compartir mi información",
    "about_key17": "Todos los derechos reservados.",
    "contact_key1": "Inicio",
    "contact_key2": "Sobre mí",
    "contact_key3": "Contacto",
    "contact_key4": "Contacto",
    "contact_key5": "Enviar Mensaje",
    "contact_key6": "¡Gracias por tu mensaje!",
    "contact_key7": "Te responderé lo antes posible.",
    "contact_key8": "Rosina Rey",
    "contact_key9": "Rosina.rey.asis@gmail.com",
    "contact_key10": "Rosina.rey.asis@gmail.com",
    "contact_key11": "+598 9820 3870",
    "contact_key12": "+598 9820 3870",
    "contact_key13": "Privacidad",
    "contact_key14": "Términos",
    "contact_key15": "Accesibilidad",
    "contact_key16": "No vender ni compartir mi información",
    "contact_key17": "Todos los derechos reservados.",
    "index_key1": "Inicio",
    "index_key2": "Sobre mí",
    "index_key3": "Contacto",
    "index_key4": "Bienvenido/a a tu espacio de terapia online",
    "index_key5": "Trabajo desde un enfoque cognitivo-conductual, de forma online, adaptando el proceso terapéutico a tus tiempos y necesidades.",
    "index_key6": "Si estás listo/a para comenzar este proceso de cambio y crecimiento, no dudes en contactarme. Juntos podemos trabajar hacia un bienestar más pleno y una vida más equilibrada.",
    "index_key7": "Agendar una Cita",
    "index_key8": "Servicios",
    "index_key9": "Rosina Rey",
    "index_key10": "Rosina.rey.asis@gmail.com",
    "index_key11": "Rosina.rey.asis@gmail.com",
    "index_key12": "+598 9820 3870",
    "index_key13": "+598 9820 3870",
    "index_key14": "Privacidad",
    "index_key15": "Términos",
    "index_key16": "Accesibilidad",
    "index_key17": "No vender ni compartir mi información",
    "index_key18": "Todos los derechos reservados.",
  },
  en: {
    "404_key1": "Home",
    "404_key2": "About Me",
    "404_key3": "Contact",
    "404_key4": "404",
    "404_key5": "Page not found",
    "404_key6": "We're sorry, the page you're looking for doesn't exist.",
    "404_key7": "Return to Home",
    "about_key1": "Home",
    "about_key2": "About Me",
    "about_key3": "Contact",
    "about_key4": "Hi, I'm Rosina. Welcome to my page! I'm a psychologist with five years of experience working with a wide variety of patients and situations.",
    "about_key5": "For two years, I was part of a psychiatric center team, which allowed me to develop strong skills in addressing diverse psychological issues.",
    "about_key6": "I have experience treating depression, separation grief, low self-esteem, bipolar disorder, anxiety disorders, borderline personality disorder, schizophrenia, addictions, among others.",
    "about_key7": "I have also worked as a professor at the University of the Republic (UDELAR) and in Human Resources.",
    "about_key8": "Currently, I dedicate myself to my true passion: providing personalized clinical care using a cognitive-behavioral approach.",
    "about_key9": "Schedule an Appointment",
    "about_key10": "Rosina Rey",
    "about_key11": "Rosina.rey.asis@gmail.com",
    "about_key12": "+598 9820 3870",
    "about_key13": "Privacy",
    "about_key14": "Terms",
    "about_key15": "Accessibility",
    "about_key16": "Do not sell or share my information",
    "about_key17": "All rights reserved",
    "contact_key1": "Home",
    "contact_key2": "About Me",
    "contact_key3": "Contact",
    "contact_key4": "Contact",
    "contact_key5": "Send Message",
    "contact_key6": "Thank you for your message!",
    "contact_key7": "I will get back to you as soon as possible.",
    "contact_key8": "Rosina Rey",
    "contact_key9": "Rosina.rey.asis@gmail.com",
    "contact_key10": "Rosina.rey.asis@gmail.com",
    "contact_key11": "+598 9820 3870",
    "contact_key12": "+598 9820 3870",
    "contact_key13": "Privacy",
    "contact_key14": "Terms",
    "contact_key15": "Accessibility",
    "contact_key16": "Do not sell or share my information",
    "contact_key17": "All rights reserved",
    "index_key1": "Home",
    "index_key2": "About Me",
    "index_key3": "Contact",
    "index_key4": "Welcome to your online therapy space",
    "index_key5": "I work from a cognitive-behavioral approach, creating a supportive and confidential space to help you achieve emotional well-being.",
    "index_key6": "If you're ready to start this journey of self-discovery and growth, I'm here to accompany you.",
    "index_key7": "Schedule an Appointment",
    "index_key8": "Services",
    "index_key9": "Rosina Rey",
    "index_key10": "Rosina.rey.asis@gmail.com",
    "index_key11": "Rosina.rey.asis@gmail.com",
    "index_key12": "+598 9820 3870",
    "index_key13": "+598 9820 3870",
    "index_key14": "Privacidad",
    "index_key15": "Terms",
    "index_key16": "Accessibility",
    "index_key17": "Do not sell or share my information",
    "index_key18": "All rights reserved",
  }
};

function translate(lang) {
  document.querySelectorAll('[data-translate]').forEach(el => {
    const key = el.getAttribute('data-translate');
    if (translations[lang] && translations[lang][key]) {
      el.innerText = translations[lang][key];
    }
  });
}

document.addEventListener("DOMContentLoaded", () => {
  const defaultLang = navigator.language.startsWith("es") ? "es" : "en";
  translate(defaultLang);

  const esFlag = document.getElementById("lang-es");
  const enFlag = document.getElementById("lang-en");

  if (esFlag) esFlag.addEventListener("click", () => translate("es"));
  if (enFlag) enFlag.addEventListener("click", () => translate("en"));
});
